FROM eclipse-temurin:17-jdk AS build

# Agrega tu código y otros pasos necesarios para tu aplicación
WORKDIR /app
COPY . .

# Puedes ejecutar comandos Maven aquí si es necesario
RUN mvn clean install
