# Usa la imagen Maven con JDK 17 preinstalado
FROM maven:3-jdk-17 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia el código fuente y el archivo pom.xml
COPY pom.xml .
COPY src ./src

# Compila el proyecto
RUN mvn clean install -DskipTests

# Define el comando de inicio
CMD ["java", "-jar", "target/mi-aplicacion.jar"]
