# Usa una imagen base de JDK 17
FROM eclipse-temurin:17-jdk AS build

# Establece el directorio de trabajo
WORKDIR /app

# Instala Maven
RUN apt-get update && apt-get install -y maven

# Copia el archivo pom.xml
COPY pom.xml .

# Copia el código fuente
COPY src ./src

# Compila el proyecto
RUN mvn clean install -DskipTests

# Define el comando de inicio
CMD ["java", "-jar", "target/itb_api-0.0.1.jar"]
